name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - test
      - 'releases/*'

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      id: check
      with:
        reviewers: kyle-west @digital-taco/admins @digital-taco/qas
        rotation: 4 Weeks
    - run: echo "reviewer is ${{ steps.check.outputs.reviewer }}"
    - run: echo "calendar is ${{ steps.check.outputs.calendar }}"
